In [490]:
import pandas as pd
import numpy as np
import csv
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LinearRegression
from random import random, randint
import matplotlib.pyplot as plt
%matplotlib inline

In [491]:
df = pd.read_csv("regLinPoli.csv")

In [492]:
X=df[['X','X2','X3','X4']]
y=df[['y']]

In [493]:
X_train, X_test, Y_train, Y_test = train_test_split(X,y, train_size=0.75)

In [494]:
len(X_train.columns)

4

In [495]:
def salida(w0,w,X):
    suma = w0
    for i in range(len(w)):
        suma = suma+w[i]*X[i]
        return suma

In [496]:
def entrena(w0,w,X_train,y,lam):
    Nu=0.01
    numerodedatos = len(X_train)
    for i in range(numerodedatos):
        sal = salida(w0,w,X_train[i])
        error = y[i]-sal
        w0 =w0+Nu*error
        nodeatributos = len(X_train[i])
        for j in range (nodeatributos):
            w[j]=w[j]+Nu*error*X_train[i][j]-lam*w[j]
    return w0,w

In [497]:
def ECM(w0,w,X_train,y):
    resECM = []
    for i in range(len(w)):
        res = sum((y-w0-w[i]*X_train[i])**2)
        resECM.append(res)
    return(resECM) 

In [498]:
from sklearn import preprocessing
escalaX=preprocessing.StandardScaler()
escalaY=preprocessing.StandardScaler()
escalaX.fit(X_train)
X_train=escalaX.transform(X_train)
escalaY.fit(Y_train)
Y_train=escalaY.transform(Y_train)
X_traina=np.array(X_train)
Y_traina=np.array(Y_train)

In [499]:
from random import random, randint
w0=random()
w=[random() for i in range(4)]

In [500]:
#Estoy dividiendo el conjunto train en dos: un nuevo train(b) y uno de validación
X_trainb, X_valida, Y_trainb, Y_valida = train_test_split(X_traina,Y_traina, train_size=0.75)

In [501]:
lam=0
lambdas=[]
errores=[]
for i in range(11):
    w0,w=entrena(w0,w,X_trainb,Y_trainb,lam)
    errorlam=ECM(w0,w,X_valida,Y_valida) #calculo el error con el conjunto de validación
    errorprom=errorprom=np.mean(errorlam)
    lambdas.append(lam)
    errores.append(errorprom)
    #No hago la gráfica porque aún no aprendo bien a graficar y no lo he logrado
    lam = lam+.01

In [502]:
lambdafinal = lambdas[errores.index(np.min(errores))]

In [503]:
X_testa=np.array(X_test)
Y_testa=np.array(Y_test)

In [504]:
errortest=[]
for i in range(10):
    w0,w=entrena(w0,w,X_traina,Y_traina,lambdafinal)
    errorcuad=ECM(w0,w,X_testa,Y_testa) #calculo el error con el conjunto test
    errorcuadprom=np.mean(errorcuad)
    errortest.append(errorcuadprom)
    #No hago la gráfica porque aún no aprendo bien a graficar y no lo he logrado

In [505]:
w0

array([-0.03464208])

In [506]:
w

[array([ 0.09086749]),
 array([ 0.09863636]),
 array([-0.00042337]),
 array([ 0.03798993])]